name: flutter_uiux_package
description: Flutter UI/UX Package for AliothX
version: 1.2.0
homepage : https://github.com/reactspring
repository: https://github.com/reactspring/flutter_uiux_package.git
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  url_launcher:
  http:

  google_fonts: ^2.3.1
  flutter_lg_health:
    path: ../../
  # 바텀시트
  bottom_sheet: ^2.0.0
  # 로딩 인디케이터
  loading_indicator: ^3.0.3
  # 페이지 인디케이터
  smooth_page_indicator: ^1.0.0+2
  # 휴대폰 번호 입력필드 
  extended_phone_number_input: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
