// ignore_for_file: deprecated_member_use

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_uiux_package/flutter_uiux_package.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

const AgnesScheme _scheme = AgnesScheme.agnes;
final ThemeData agnesThemeLight = AgnesThemeData.light(
  scheme: _scheme,
  blendLevel: 18,
  appBarStyle: AgnesAppBarStyle.primary,
  appBarOpacity: 1,
  appBarElevation: 0,
  bottomAppBarElevation: 5.0,
  transparentStatusBar: true,
  tabBarStyle: AgnesTabBarStyle.forBackground,
  tooltipsMatchBackground: true,
  swapColors: false,
  useSubThemes: true,
  textTheme: textTheme,
  primaryTextTheme: textTheme,
  visualDensity: AgnesColorScheme.comfortablePlatformDensity,
  subThemesData: const AgnesSubThemesData(
    useTextTheme: true,
    fabUseShape: true,
    interactionEffects: true,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderType: AgnesInputBorderType.outline,
    inputDecoratorUnfocusedHasBorder: true,
    blendOnColors: true,
    popupMenuOpacity: 0.95,
    elevatedButtonElevation: 1,
    bottomSheetElevation: kBottomSheetElevation,
    bottomSheetModalElevation: kBottomSheetModalElevation,
    bottomNavigationBarElevation: kBottomNavigationBarElevation,
    bottomNavigationBarOpacity: 0.8,
    navigationBarMutedUnselectedText: true,
    navigationBarMutedUnselectedIcon: true,
    navigationBarSelectedLabelSize: 12,
    navigationBarUnselectedLabelSize: 10,
    navigationBarSelectedIconSize: 26,
    navigationBarUnselectedIconSize: 24,
    navigationBarLabelBehavior: NavigationDestinationLabelBehavior.alwaysShow,
  ),
);

final ThemeData agnesThemeDark = AgnesThemeData.dark(
  scheme: _scheme,
  surfaceMode: AgnesSurfaceMode.highScaffoldLowSurface,
  blendLevel: 18,
  appBarStyle: AgnesAppBarStyle.background,
  appBarOpacity: 0.95,
  appBarElevation: 0,
  transparentStatusBar: true,
  tabBarStyle: AgnesTabBarStyle.forAppBar,
  tooltipsMatchBackground: true,
  swapColors: false,
  darkIsTrueBlack: false,
  useSubThemes: true,
  visualDensity: AgnesColorScheme.comfortablePlatformDensity,
  textTheme: textTheme,
  primaryTextTheme: textTheme,
  // To use playground font, add GoogleFonts package and uncomment:
  // fontFamily: GoogleFonts.notoSans().fontFamily,
  subThemesData: const AgnesSubThemesData(
    useTextTheme: true,
    fabUseShape: true,
    interactionEffects: true,
    inputDecoratorIsFilled: true,
    inputDecoratorBorderType: AgnesInputBorderType.outline,
    inputDecoratorUnfocusedHasBorder: true,
    blendOnColors: true,
    blendTextTheme: true,
    popupMenuOpacity: 0.95,
    elevatedButtonElevation: 1,
    bottomSheetElevation: kBottomSheetElevation,
    bottomSheetModalElevation: kBottomSheetModalElevation,
    bottomNavigationBarElevation: kBottomNavigationBarElevation,
    bottomNavigationBarOpacity: 0.95,
    bottomNavigationBarBackgroundSchemeColor: SchemeColor.background,
    navigationBarIsStyled: true,
    navigationBarHeight: 80,
    navigationBarOpacity: 0.95,
    bottomNavigationBarSchemeColor: SchemeColor.onSurface,
    navigationBarIconSchemeColor: SchemeColor.onSurface,
    navigationBarTextSchemeColor: SchemeColor.onSurface,
    navigationBarHighlightSchemeColor: SchemeColor.onSurface,
    navigationBarMutedUnselectedText: true,
    navigationBarMutedUnselectedIcon: true,
    navigationBarBackgroundSchemeColor: SchemeColor.background,
    navigationBarSelectedLabelSize: 12,
    navigationBarUnselectedLabelSize: 10,
    navigationBarSelectedIconSize: 26,
    navigationBarUnselectedIconSize: 24,
    navigationBarLabelBehavior:
        NavigationDestinationLabelBehavior.onlyShowSelected,
  ),
);
var textTheme = TextTheme(
  headline1:
      TextStyle(fontWeight: FontWeight.w700, fontSize: 34.0.sp, height: 1.25),
  headline2:
      TextStyle(fontWeight: FontWeight.w700, fontSize: 30.0.sp, height: 1.25),
  headline3:
      TextStyle(fontWeight: FontWeight.w700, fontSize: 26.0.sp, height: 1.25),
  headline4:
      TextStyle(fontWeight: FontWeight.w700, fontSize: 22.0.sp, height: 1.25),
  headline5:
      TextStyle(fontWeight: FontWeight.w700, fontSize: 20.0.sp, height: 1.25),
  headline6: TextStyle(
      fontWeight: FontWeight.w700,
      fontSize: 18.0.sp,
      height: 1.25,
      letterSpacing: -0.4),
  subtitle1: TextStyle(
    fontWeight: FontWeight.w600,
    fontSize: 16.0.sp,
    height: 1.25,
  ),
  subtitle2: TextStyle(
      fontWeight: FontWeight.w600,
      fontSize: 14.0.sp,
      height: 1.25,
      letterSpacing: -0.4),
  bodyText1: TextStyle(
      fontWeight: FontWeight.w400,
      fontSize: 16.0.sp,
      height: 1.25,
      letterSpacing: -0.4),
  bodyText2: TextStyle(
      fontWeight: FontWeight.w400,
      fontSize: 14.0.sp,
      height: 1.25,
      letterSpacing: -0.4),
  caption: TextStyle(
      fontWeight: FontWeight.w400,
      fontSize: 13.sp,
      height: 1.5,
      letterSpacing: -0.3),
  overline: TextStyle(
      fontWeight: FontWeight.w400,
      fontSize: 11.sp,
      height: 1.5,
      letterSpacing: -0.3),
);

/// 정의하는 ThemeData
///
/// 이곳에 상세하게 ThemeData를 적용하는 예제 작성하기
/// ui 보여주고 테마 적용에 관한건 웹에서 하도록? -> 코드 복붙
/// https://rxlabz.github.io/panache/#/editor 이것처럼
ThemeData agnesTheme = ThemeData(
  androidOverscrollIndicator: AndroidOverscrollIndicator.glow,
  applyElevationOverlayColor: true,
  cupertinoOverrideTheme: NoDefaultCupertinoThemeData(),

  /*
  AndroidOverscrollIndicator? androidOverscrollIndicator,
  bool? applyElevationOverlayColor,
  NoDefaultCupertinoThemeData? cupertinoOverrideTheme,
  InputDecorationTheme? inputDecorationTheme,
  MaterialTapTargetSize? materialTapTargetSize,
  PageTransitionsTheme? pageTransitionsTheme,
  TargetPlatform? platform,
  ScrollbarThemeData? scrollbarTheme,
  InteractiveInkFeatureFactory? splashFactory,
  VisualDensity? visualDensity,
  bool? useMaterial3,
  ColorScheme? colorScheme,
  Color? colorSchemeSeed,
  Brightness? brightness,
  MaterialColor? primarySwatch,
  Color? primaryColor,
  Color? primaryColorLight,
  Color? primaryColorDark,
  Color? focusColor,
  Color? hoverColor,
  Color? shadowColor,
  Color? canvasColor,
  Color? scaffoldBackgroundColor,
  Color? bottomAppBarColor,
  Color? cardColor,
  Color? dividerColor,
  Color? highlightColor,
  Color? splashColor,
  Color? selectedRowColor,
  Color? unselectedWidgetColor,
  Color? disabledColor,
  Color? secondaryHeaderColor,
  Color? backgroundColor,
  Color? dialogBackgroundColor,
  Color? indicatorColor,
  Color? hintColor,
  Color? errorColor,
  Color? toggleableActiveColor,
  String? fontFamily,
  Typography? typography,
  TextTheme? textTheme,
  TextTheme? primaryTextTheme,
  IconThemeData? iconTheme,
  IconThemeData? primaryIconTheme,
  AppBarTheme? appBarTheme,
  MaterialBannerThemeData? bannerTheme,
  BottomAppBarTheme? bottomAppBarTheme,
  BottomNavigationBarThemeData? bottomNavigationBarTheme,
  BottomSheetThemeData? bottomSheetTheme,
  ButtonBarThemeData? buttonBarTheme,
  ButtonThemeData? buttonTheme,
  CardTheme? cardTheme,
  CheckboxThemeData? checkboxTheme,
  ChipThemeData? chipTheme,
  DataTableThemeData? dataTableTheme,
  DialogTheme? dialogTheme,
  DividerThemeData? dividerTheme,
  DrawerThemeData? drawerTheme,
  ElevatedButtonThemeData? elevatedButtonTheme,
  FloatingActionButtonThemeData? floatingActionButtonTheme,
  ListTileThemeData? listTileTheme,
  NavigationBarThemeData? navigationBarTheme,
  NavigationRailThemeData? navigationRailTheme,
  OutlinedButtonThemeData? outlinedButtonTheme,
  PopupMenuThemeData? popupMenuTheme,
  ProgressIndicatorThemeData? progressIndicatorTheme,
  RadioThemeData? radioTheme,
  SliderThemeData? sliderTheme,
  SnackBarThemeData? snackBarTheme,
  SwitchThemeData? switchTheme,
  TabBarTheme? tabBarTheme,
  TextButtonThemeData? textButtonTheme,
  TextSelectionThemeData? textSelectionTheme,
  TimePickerThemeData? timePickerTheme,
  ToggleButtonsThemeData? toggleButtonsTheme,
  TooltipThemeData? tooltipTheme,
  bool? useTextSelectionTheme,
  Color? textSelectionColor,
  Color? cursorColor,
  Color? textSelectionHandleColor,
  Color? accentColor,
  Brightness? accentColorBrightness,
  TextTheme? accentTextTheme,
  IconThemeData? accentIconTheme,
  Color? buttonColor,
  bool? fixTextFieldOutlineLabel,
  Brightness? primaryColorBrightness,
  */
);
